# Generated by Django 5.1.7 on 2025-04-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
